micronaut:
  application:
    name: gateway
#  http:
#    services:
#      books:
#        url: 'http://books:8080'
endpoints:
  info:
    enabled: true
    sensitive: false
  health:
    enabled: true
    details-visible: ANONYMOUS
